# Generated by Django 4.0.3 on 2022-04-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Color1',
            fields=[
                ('Client_id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_Year', models.IntegerField()),
                ('Client_sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский'), ('другой', 'другой')], max_length=10)),
                ('Client_country1', models.CharField(max_length=50)),
                ('Client_country2', models.CharField(max_length=50)),
                ('Client_lang', models.CharField(max_length=50)),
                ('Client_edu', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=10)),
                ('Client_shade', models.CharField(choices=[('да', 'да'), ('нет', 'нет')], max_length=10)),
                ('color1', models.CharField(max_length=10)),
                ('color2', models.CharField(max_length=10)),
                ('color3', models.CharField(max_length=10)),
                ('color4', models.CharField(max_length=10)),
                ('color5', models.CharField(max_length=10)),
                ('left1', models.CharField(max_length=5)),
                ('left2', models.CharField(max_length=5)),
                ('left3', models.CharField(max_length=5)),
                ('left4', models.CharField(max_length=5)),
                ('left5', models.CharField(max_length=5)),
                ('left6', models.CharField(max_length=5)),
                ('left7', models.CharField(max_length=5)),
                ('left8', models.CharField(max_length=5)),
                ('left9', models.CharField(max_length=5)),
                ('left10', models.CharField(max_length=5)),
            ],
        ),
    ]
