# Generated by Django 4.0.3 on 2022-05-24 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_color1',
            name='Client_Year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1920)]),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='color1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='color2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='color3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='color4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='color5',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left10',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left5',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left6',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left7',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left8',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='left9',
            field=models.CharField(max_length=20),
        ),
    ]
