# Generated by Django 4.0.3 on 2022-05-24 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_color1_client_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_color1',
            name='Client_Year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1920)]),
        ),
    ]
