# Generated by Django 4.0.3 on 2022-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_color1_client_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_color1',
            name='Client_Year',
            field=models.IntegerField(),
        ),
    ]
