# Generated by Django 4.1.1 on 2022-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_color1_client_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_color1',
            name='Client_country1',
            field=models.CharField(choices=[('Algeria', 'Algeria'), ('Australia', 'Australia'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Azerbaijan', 'Azerbaijan'), ('Belarus', 'Belarus'), ('Brazil', 'Brazil'), ('Belgium', 'Belgium'), ('Bulgaria', 'Bulgaria'), ('Chile', 'Chile'), ('Czech Republic', 'Czech Republic'), ('China', 'China'), ('Croatia', 'Croatia'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('India', 'India'), ('Iran', 'Iran'), ('Japan', 'Japan'), ('Korea', 'Korea'), ('Latvia', 'Latvia'), ('Mexico', 'Mexico'), ('Nigeria', 'Nigeria'), ('Namibia', 'Namibia'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Russia', 'Russia'), ('Spain', 'Spain'), ('Saudi Arabia', 'Saudi Arabia'), ('Serbia', 'Serbia'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Turkey', 'Turkey'), ('Thailand', 'Thailand'), ('Tunis', 'Tunis'), ('United Kingdom ', 'United Kingdom'), ('USA', 'USA'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='Client_country2',
            field=models.CharField(choices=[('Algeria', 'Algeria'), ('Australia', 'Australia'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Azerbaijan', 'Azerbaijan'), ('Belarus', 'Belarus'), ('Brazil', 'Brazil'), ('Belgium', 'Belgium'), ('Bulgaria', 'Bulgaria'), ('Chile', 'Chile'), ('Czech Republic', 'Czech Republic'), ('China', 'China'), ('Croatia', 'Croatia'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('India', 'India'), ('Iran', 'Iran'), ('Japan', 'Japan'), ('Korea', 'Korea'), ('Latvia', 'Latvia'), ('Mexico', 'Mexico'), ('Nigeria', 'Nigeria'), ('Namibia', 'Namibia'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Russia', 'Russia'), ('Spain', 'Spain'), ('Saudi Arabia', 'Saudi Arabia'), ('Serbia', 'Serbia'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Turkey', 'Turkey'), ('Thailand', 'Thailand'), ('Tunis', 'Tunis'), ('United Kingdom ', 'United Kingdom'), ('USA', 'USA'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='Client_edu',
            field=models.CharField(choices=[('да', 'yes, да, si'), ('нет', 'no, нет, no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='Client_sex',
            field=models.CharField(choices=[('мужской', 'male, мужской, masculino'), ('женский', 'female, женский, femenino'), ('другой', 'other, другой, otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='Client_shade',
            field=models.CharField(choices=[('да', 'yes, да, si'), ('нет', 'no, нет, no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='client_color1',
            name='color1',
            field=models.CharField(max_length=50),
        ),
    ]
