# Generated by Django 3.2.16 on 2025-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20250518_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_color2',
            name='color_dislike',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client_color2',
            name='color_like',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='color1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='color2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='color3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='color4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='color5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left10',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left6',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left7',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left8',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client_color2',
            name='left9',
            field=models.CharField(default='', max_length=20),
        ),
    ]
