# Generated by Django 3.2.16 on 2025-06-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20250609_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_color2',
            name='Client_lang',
        ),
    ]
