# Generated by Django 3.2.16 on 2026-10-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20260708_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_color1',
            name='color_dislike',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client_color1',
            name='color_like',
            field=models.CharField(default='', max_length=20),
        ),
    ]
