"""
Адресация приложения,
для каждой страницы - свой адрес
"""
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('page1/', views.indexLn, name='indexLn'),
    path('page2/', views.index1, name='index1'),
    path('page3/', views.index2, name='index2'),
    path('page4/', views.index3, name='index3'),
    path('page5/', views.index4, name='index4'),
    path('page6/', views.index5, name='index5'),
    path('page7/', views.index6, name='index6'),
    path('page8/', views.index7, name='index7'),
    path('page9/', views.index8, name='index8'),
    path('page10/', views.index9, name='index9'),
    path('page11/', views.index10, name='index10'),
    path('page12/', views.index11, name='index11'),
    path('page13/', views.index12, name='index12'),
    path('page14/', views.index13, name='index13'),
    path('page15/', views.index14, name='index14'),
    path('page_end/', views.index15, name='index15'),
    path('indexend/', views.indexend, name='indexend'),
    path('export_xls/', views.export_xls, name='export_xls'),
    path('russias_regions/experiment', views.russias_regions, name='russias_regions'),
    path('russias_regions/dislike_color/', views.fav_color, name='fav_color'),
    path('russias_regions/mtable1/', views.dislike_color, name='dislike_color'),
    path('russias_regions/mtable2/', views.mtable1, name='mtable1'),
    path('russias_regions/mtable3/', views.mtable2, name='mtable2'),
    path('russias_regions/mtable4/', views.mtable3, name='mtable3'),
    path('russias_regions/mtable5/', views.mtable4, name='mtable4'),
    path('russias_regions/choice1/', views.mtable5, name='mtable5'),
    path('russias_regions/choice2/', views.choice1, name='choice1'),
    path('russias_regions/choice3/', views.choice2, name='choice2'),
    path('russias_regions/choice4/', views.choice3, name='choice3'),
    path('russias_regions/choice5/', views.choice4, name='choice4'),
    path('russias_regions/choice6/', views.choice5, name='choice5'),
    path('russias_regions/choice7/', views.choice6, name='choice6'),
    path('russias_regions/choice8/', views.choice7, name='choice7'),
    path('russias_regions/choice9/', views.choice8, name='choice8'),
    path('russias_regions/choice10/', views.choice9, name='choice9'),
    path('russias_regions/choice_end/', views.choice10, name='choice10'),
    path('export_regions_xls/', views.export_regions_xls, name='export_regions_xls'),
]
